class CurrencyUnit {
  final String currencyCode;
  final String displayName;
  final String currencySymbol;

  const CurrencyUnit(this.currencyCode, this.displayName,
      [this.currencySymbol]);
}

const Map<String, CurrencyUnit> availableCurrencyUnits = {
  'AED': CurrencyUnit('AED', 'United Arab Emirates Dirham'),
  'AFN': CurrencyUnit('AFN', 'Afghan Afghani'),
  'ALL': CurrencyUnit('ALL', 'Albanian Lek'),
  'AMD': CurrencyUnit('AMD', 'Armenian Dram'),
  'ANG': CurrencyUnit('ANG', 'Netherlands Antillean Guilder'),
  'AOA': CurrencyUnit('AOA', 'Angolan Kwanza'),
  'ARS': CurrencyUnit('ARS', 'Argentine Peso'),
  'ATS': CurrencyUnit('ATS', 'Austrian Schilling'),
  'AUD': CurrencyUnit('AUD', 'Australian Dollar'),
  'AWG': CurrencyUnit('AWG', 'Aruban Florin'),
  'AZN': CurrencyUnit('AZN', 'Azerbaijani Manat'),
  'BAM': CurrencyUnit('BAM', 'Bosnia And Herzegovina Convertible Mark'),
  'BBD': CurrencyUnit('BBD', 'Barbados Dollar'),
  'BDT': CurrencyUnit('BDT', 'Bangladeshi Taka'),
  'BGN': CurrencyUnit('BGN', 'Bulgarian Lev'),
  'BHD': CurrencyUnit('BHD', 'Bahraini Dinar'),
  'BIF': CurrencyUnit('BIF', 'Burundian Franc'),
  'BMD': CurrencyUnit('BMD', 'Bermudian Dollar'),
  'BND': CurrencyUnit('BND', 'Brunei Dollar'),
  'BOB': CurrencyUnit('BOB', 'Boliviano'),
  'BRL': CurrencyUnit('BRL', 'Brazilian Real'),
  'BSD': CurrencyUnit('BSD', 'Bahamian Dollar'),
  'BTN': CurrencyUnit('BTN', 'Bhutanese Ngultrum'),
  'BWP': CurrencyUnit('BWP', 'Botswana Pula'),
  'BYN': CurrencyUnit('BYN', 'Belarusian Ruble'),
  'BZD': CurrencyUnit('BZD', 'Belize Dollar'),
  'CAD': CurrencyUnit('CAD', 'Canadian Dollar'),
  'CDF': CurrencyUnit('CDF', 'Congolese Franc'),
  'CHF': CurrencyUnit('CHF', 'Swiss Franc'),
  'CLP': CurrencyUnit('CLP', 'Chilean Peso'),
  'CNY': CurrencyUnit('CNY', 'Chinese Yuan Renminbi'),
  'COP': CurrencyUnit('COP', 'Colombian Peso'),
  'CRC': CurrencyUnit('CRC', 'Costa Rican Colon'),
  'CUC': CurrencyUnit('CUC', 'Cuban Convertible Peso'),
  'CUP': CurrencyUnit('CUP', 'Cuban Peso'),
  'CVE': CurrencyUnit('CVE', 'Cape Verde Escudo'),
  'CZK': CurrencyUnit('CZK', 'Czech Koruna'),
  'DEM': CurrencyUnit('DEM', 'German mark'),
  'DJF': CurrencyUnit('DJF', 'Djiboutian Franc'),
  'DKK': CurrencyUnit('DKK', 'Danish Krone'),
  'DOP': CurrencyUnit('DOP', 'Dominican Peso'),
  'DZD': CurrencyUnit('DZD', 'Algerian Dinar'),
  'EGP': CurrencyUnit('EGP', 'Egyptian Pound'),
  'ERN': CurrencyUnit('ERN', 'Eritrean Nakfa'),
  'ETB': CurrencyUnit('ETB', 'Ethiopian Birr'),
  'EUR': CurrencyUnit('EUR', 'Euro', '\u20AC'),
  'FJD': CurrencyUnit('FJD', 'Fiji Dollar'),
  'FKP': CurrencyUnit('FKP', 'Falkland Islands Pound'),
  'GBP': CurrencyUnit('GBP', 'British Pound Sterling', '\u00A3'),
  'GBX': CurrencyUnit('GBX', 'British Pence Sterling'),
  'GEL': CurrencyUnit('GEL', 'Georgian Lari'),
  'GHS': CurrencyUnit('GHS', 'Ghanaian Cedi'),
  'GIP': CurrencyUnit('GIP', 'Gibraltar Pound'),
  'GMD': CurrencyUnit('GMD', 'Gambian Dalasi'),
  'GNF': CurrencyUnit('GNF', 'Guinean Franc'),
  'GTQ': CurrencyUnit('GTQ', 'Guatemalan Quetzal'),
  'GYD': CurrencyUnit('GYD', 'Guyanese Dollar'),
  'HKD': CurrencyUnit('HKD', 'Hong Kong Dollar'),
  'HNL': CurrencyUnit('HNL', 'Honduran Lempira'),
  'HRK': CurrencyUnit('HRK', 'Croatian Kuna'),
  'HTG': CurrencyUnit('HTG', 'Haitian Gourde'),
  'HUF': CurrencyUnit('HUF', 'Hungarian Forint'),
  'IDR': CurrencyUnit('IDR', 'Indonesian Rupiah'),
  'ILA': CurrencyUnit('ILA', 'Israeli agora'),
  'ILS': CurrencyUnit('ILS', 'Israeli Shekel'),
  'INR': CurrencyUnit('INR', 'Indian Rupee'),
  'IQD': CurrencyUnit('IQD', 'Iraqi Dinar'),
  'IRR': CurrencyUnit('IRR', 'Iranian Rial'),
  'ISK': CurrencyUnit('ISK', 'Icelandic Kr\u00F3na'),
  'JMD': CurrencyUnit('JMD', 'Jamaican Dollar'),
  'JOD': CurrencyUnit('JOD', 'Jordanian Dinar'),
  'JPY': CurrencyUnit('JPY', 'Japanese Yen', '\u00A5'),
  'KES': CurrencyUnit('KES', 'Kenyan Shilling'),
  'KGS': CurrencyUnit('KGS', 'Kyrgyzstani Som'),
  'KHR': CurrencyUnit('KHR', 'Cambodian Riel'),
  'KMF': CurrencyUnit('KMF', 'Comoro Franc'),
  'KPW': CurrencyUnit('KPW', 'North Korean Won'),
  'KRW': CurrencyUnit('KRW', 'South Korean Won'),
  'KWD': CurrencyUnit('KWD', 'Kuwaiti Dinar'),
  'KYD': CurrencyUnit('KYD', 'Cayman Islands Dollar'),
  'KZT': CurrencyUnit('KZT', 'Kazakhstani Tenge'),
  'LAK': CurrencyUnit('LAK', 'Lao Kip'),
  'LBP': CurrencyUnit('LBP', 'Lebanese Pound'),
  'LKR': CurrencyUnit('LKR', 'Sri Lankan Rupee'),
  'LRD': CurrencyUnit('LRD', 'Liberian Dollar'),
  'LSL': CurrencyUnit('LSL', 'Lesotho Loti'),
  'LVL': CurrencyUnit('LVL', 'Latvian Lats'),
  'LYD': CurrencyUnit('LYD', 'Libyan Dinar'),
  'MAD': CurrencyUnit('MAD', 'Moroccan Dirham'),
  'MDL': CurrencyUnit('MDL', 'Moldovan Leu'),
  'MGA': CurrencyUnit('MGA', 'Malagasy Ariary'),
  'MKD': CurrencyUnit('MKD', 'Macedonian Denar'),
  'MMK': CurrencyUnit('MMK', 'Myanmar Kyat'),
  'MNT': CurrencyUnit('MNT', 'Mongolian T\u00F6gr\u00F6g'),
  'MOP': CurrencyUnit('MOP', 'Macanese Pataca'),
  'MRU': CurrencyUnit('MRU', 'Mauritanian Ouguiya'),
  'MUR': CurrencyUnit('MUR', 'Mauritian Rupee'),
  'MVR': CurrencyUnit('MVR', 'Maldivian Rufiyaa'),
  'MWK': CurrencyUnit('MWK', 'Malawian Kwacha'),
  'MXN': CurrencyUnit('MXN', 'Mexican Peso'),
  'MYR': CurrencyUnit('MYR', 'Malaysian Ringgit'),
  'MZN': CurrencyUnit('MZN', 'Mozambican Metical'),
  'NAD': CurrencyUnit('NAD', 'Namibian Dollar'),
  'NGN': CurrencyUnit('NGN', 'Nigerian Naira'),
  'NIO': CurrencyUnit('NIO', 'Nicaraguan C\u00F3rdoba'),
  'NOK': CurrencyUnit('NOK', 'Norwegian Krone'),
  'NPR': CurrencyUnit('NPR', 'Nepalese Rupee'),
  'NZD': CurrencyUnit('NZD', 'New Zealand Dollar'),
  'OMR': CurrencyUnit('OMR', 'Omani Rial'),
  'PAB': CurrencyUnit('PAB', 'Panamanian Balboa'),
  'PEN': CurrencyUnit('PEN', 'Peruvian Sol'),
  'PGK': CurrencyUnit('PGK', 'Papua New Guinean Kina'),
  'PHP': CurrencyUnit('PHP', 'Philippine Peso'),
  'PKR': CurrencyUnit('PKR', 'Pakistani Rupee'),
  'PLN': CurrencyUnit('PLN', 'Polish Zloty'),
  'PYG': CurrencyUnit('PYG', 'Paraguayan Guaran\u00ED'),
  'QAR': CurrencyUnit('QAR', 'Qatari Riyal'),
  'RON': CurrencyUnit('RON', 'Romanian Leu'),
  'RSD': CurrencyUnit('RSD', 'Serbian Dinar'),
  'RUB': CurrencyUnit('RUB', 'Russian Ruble'),
  'RWF': CurrencyUnit('RWF', 'Rwandan Franc'),
  'SAR': CurrencyUnit('SAR', 'Saudi Riyal'),
  'SBD': CurrencyUnit('SBD', 'Solomon Islands Dollar'),
  'SCR': CurrencyUnit('SCR', 'Seychelles Rupee'),
  'SDG': CurrencyUnit('SDG', 'Sudanese Pound'),
  'SEK': CurrencyUnit('SEK', 'Swedish Krona'),
  'SGD': CurrencyUnit('SGD', 'Singapore Dollar'),
  'SHP': CurrencyUnit('SHP', 'Saint Helena Pound'),
  'SLL': CurrencyUnit('SLL', 'Sierra Leonean Leone'),
  'SOS': CurrencyUnit('SOS', 'Somali Shilling'),
  'SRD': CurrencyUnit('SRD', 'Surinamese Dollar'),
  'SSP': CurrencyUnit('SSP', 'South Sudanese Pound'),
  'STN': CurrencyUnit('STN', 'S\u00E3o Tom\u00E9 And Pr\u00EDncipe Dobra'),
  'SVC': CurrencyUnit('SVC', 'Salvadoran Col\u00F3n'),
  'SYP': CurrencyUnit('SYP', 'Syrian Pound'),
  'SZL': CurrencyUnit('SZL', 'Swazi Lilangeni'),
  'THB': CurrencyUnit('THB', 'Thai Baht'),
  'TJS': CurrencyUnit('TJS', 'Tajikistani Somoni'),
  'TMT': CurrencyUnit('TMT', 'Turkmenistan Manat'),
  'TND': CurrencyUnit('TND', 'Tunisian Dinar'),
  'TOP': CurrencyUnit('TOP', 'Tongan Pa\u02BBanga'),
  'TRY': CurrencyUnit('TRY', 'Turkish Lira'),
  'TTD': CurrencyUnit('TTD', 'Trinidad And Tobago Dollar'),
  'TWD': CurrencyUnit('TWD', 'New Taiwan Dollar'),
  'TZS': CurrencyUnit('TZS', 'Tanzanian Shilling'),
  'UAH': CurrencyUnit('UAH', 'Ukrainian Hryvnia'),
  'UGX': CurrencyUnit('UGX', 'Ugandan Shilling'),
  'USD': CurrencyUnit('USD', 'United States Dollar', '\$'),
  'UYU': CurrencyUnit('UYU', 'Uruguayan Peso'),
  'UZS': CurrencyUnit('UZS', 'Uzbekistan Som'),
  'VEF': CurrencyUnit('VEF', 'Venezuelan Bol\u00EDvar'),
  'VND': CurrencyUnit('VND', 'Vietnamese \u0110\u1ED3ng'),
  'VUV': CurrencyUnit('VUV', 'Vanuatu Vatu'),
  'WST': CurrencyUnit('WST', 'Samoan Tala'),
  'YER': CurrencyUnit('YER', 'Yemeni Rial'),
  'ZAR': CurrencyUnit('ZAR', 'South African Rand'),
  'ZMW': CurrencyUnit('ZMW', 'Zambian Kwacha'),
  'ZWL': CurrencyUnit('ZWL', 'Zimbabwean Dollar'),
};
